### ISSUE TITLE
Add requestAnimationFrame

### ISSUE THREAD

**Issue by thomasbonte** [musescore/musescore-connect#5]
Stop the carroussel when the Start Center window is not displayed.

**Comment by frankbaele** [comment]
This will only work if there is no focus on the tab. Have no idea how its going to behave with het node webkit bundle

**Comment by thomasbonte** [comment]
It's not working as expected.

**Comment by thomasbonte** [comment]
Apparently requestAnimation frame is not solving the issue. The Connect carroussel keeps running.

Alternative: https://www.w3.org/TR/page-visibility/

**Comment by thomasbonte** [comment]
Let's change the carrousel speed to 1min frequency
